import { parseCodeBlocks, ensureFencesOnOwnLines } from "~/lib/data-blocks/parse"
import { fillMissingIds, buildGeneratedIdsList, type GeneratedId } from "~/lib/data-blocks/uuid"
import {
  validateStructural,
  validateSemantic,
  type ValidationError,
} from "~/lib/data-blocks/validate"
import { stampActors } from "~/lib/data-blocks/actor"
import { isSingleton } from "~/lib/data-blocks/registry"
import type { ValidationContext } from "~/lib/data-blocks/validate"
import { getFiles } from "~/lib/files/store"
import { getAllCodes } from "~/domain/data-blocks/callout/codes/selectors"
import { getTagDefinitions } from "~/domain/data-blocks/settings/tags/selectors"
import { getTags } from "~/domain/data-blocks/attributes/tags/selectors"
import { getSettings } from "~/domain/data-blocks/settings/selectors"
import { SETTINGS_FILE, isCompanionFile } from "~/lib/files/filename"
import { detectDanglingReferences } from "~/lib/data-blocks/refs"

export type FileResult =
  | { path: string; status: "ok"; content: string; generatedIds?: GeneratedId[] }
  | {
      path: string
      status: "partial"
      content: string
      warnings: string
      generatedIds?: GeneratedId[]
    }
  | { path: string; status: "error"; error: string; blockErrors?: ValidationError[] }

const formatBlock = (language: string, content: string): string =>
  `\`\`\`${language}\n${content}\n\`\`\``

const enrichStructuralErrors = (
  errors: ValidationError[],
  originalMarkdown: string | undefined
): ValidationError[] => {
  if (!originalMarkdown) return errors
  const originals = parseCodeBlocks(originalMarkdown)
  return errors.map((err) => {
    if (!isSingleton(err.block)) return err
    const original = originals.find((b) => b.language === err.block)
    if (!original) return err
    return { ...err, currentBlock: formatBlock(original.language, original.content) }
  })
}

const buildValidationContext = (): ValidationContext => ({
  availableCodes: getAllCodes(getFiles()).map((c) => ({ id: c.id, name: c.title })),
  availableTags: getTagDefinitions(getFiles()).map((t) => ({ id: t.id, label: t.label })),
})

const errorKey = (e: ValidationError): string =>
  [e.block, e.field ?? "", e.message, e.received ?? ""].join("|")

// A write may only be blocked by invalidity it introduces. Errors the file already
// had (draft blocks inserted empty, awaiting their fields) would otherwise deadlock
// every single-block patch or delete while a sibling draft exists.
const withoutPreexisting = (
  errors: ValidationError[],
  path: string,
  original: string | undefined,
  skipImmutableCheck: boolean | undefined
): ValidationError[] => {
  if (!original) return errors
  const baseline = validateSemantic(original, {
    path,
    context: buildValidationContext(),
    original,
    skipImmutableCheck,
  })
  if (baseline.errors.length === 0) return errors
  const known = new Set(baseline.errors.map(errorKey))
  return errors.filter((e) => !known.has(errorKey(e)))
}

const formatBlockErrors = (errors: ValidationError[]): string =>
  errors
    .map((e) => {
      const location = e.field ? `${e.block}.${e.field}` : e.block
      const received = e.received ? ` (received: ${e.received})` : ""
      const hint = e.hint ? ` Available: ${JSON.stringify(e.hint)}` : ""
      const current = e.currentBlock ? `\nCurrent block:\n${e.currentBlock}` : ""
      return `${location}: ${e.message}${received}${hint}${current}`
    })
    .join("\n")

const buildTagReferenceMap = (
  files: Record<string, string>,
  excludePath: string
): Map<string, string[]> => {
  const refs = new Map<string, string[]>()
  for (const [path, content] of Object.entries(files)) {
    if (path === excludePath) continue
    for (const tagId of getTags(content)) {
      refs.set(tagId, [...(refs.get(tagId) ?? []), path])
    }
  }
  return refs
}

interface FinalizeContentOptions {
  original: string
  actor?: "ai" | "user"
  skipImmutableCheck?: boolean
  skipSemanticValidation?: boolean
  skipBlockValidation?: boolean
  placeholderIds?: Record<string, string>
}

export const finalizeContent = (
  path: string,
  content: string,
  options: FinalizeContentOptions
): FileResult => {
  const { content: filledContent, generated: autoGenerated } = fillMissingIds(
    content,
    options.original
  )
  const stampedContent = options.actor
    ? stampActors(options.original, filledContent, options.actor)
    : filledContent
  const sanitizedContent = ensureFencesOnOwnLines(stampedContent)

  // Companion files (per-source embedding vectors) are programmatic — written only by
  // lib/embeddings/sync.ts via buildCompanionMarkdown. No user/agent editing. Schema parsing
  // 1024-float arrays per block is purely waste, and any "failure" here can't be acted on
  // since the source of truth is the embeddings sync, not the patch path.
  // Tool callers that guarantee block bytes are untouched (e.g. edit_file with masking)
  // can opt in via options.skipBlockValidation.
  const skipBlockValidation = isCompanionFile(path) || options.skipBlockValidation === true

  if (!skipBlockValidation) {
    const structuralErrors = validateStructural(sanitizedContent)
    if (structuralErrors.length > 0) {
      const enriched = enrichStructuralErrors(structuralErrors, options.original)
      return {
        path,
        status: "error",
        error: formatBlockErrors(enriched),
        blockErrors: enriched,
      }
    }
  }

  const validation = skipBlockValidation
    ? { valid: true, errors: [], warnings: [], recoveredMarkdown: undefined }
    : validateSemantic(sanitizedContent, {
        path,
        context: buildValidationContext(),
        original: options.original,
        skipImmutableCheck: options.skipImmutableCheck,
      })

  const blockingErrors = validation.valid
    ? []
    : withoutPreexisting(validation.errors, path, options.original, options.skipImmutableCheck)

  if (blockingErrors.length > 0) {
    if (options.skipSemanticValidation) {
      console.warn(
        `[patch] semantic validation warnings for "${path}":`,
        formatBlockErrors(blockingErrors)
      )
    } else {
      return {
        path,
        status: "error",
        error: formatBlockErrors(blockingErrors),
        blockErrors: blockingErrors,
      }
    }
  }

  const finalContent = validation.recoveredMarkdown ?? sanitizedContent

  if (options.original && path === SETTINGS_FILE) {
    const files = getFiles()
    const oldTagIds = getTagDefinitions(files).map((t) => t.id)
    const newTagIds = (getSettings(finalContent)?.tags ?? []).map((t) => t.id)
    const refs = buildTagReferenceMap(files, path)
    const refErrors = detectDanglingReferences(oldTagIds, newTagIds, refs)
    if (refErrors.length > 0) {
      return { path, status: "error", error: formatBlockErrors(refErrors), blockErrors: refErrors }
    }
  }

  const generatedIds = buildGeneratedIdsList(
    options.placeholderIds ?? {},
    autoGenerated,
    finalContent
  )

  const hasWarnings = validation.warnings.length > 0

  if (hasWarnings) {
    return {
      path,
      status: "partial",
      content: finalContent,
      warnings: validation.warnings.join("\n"),
      ...(generatedIds.length > 0 && { generatedIds }),
    }
  }

  return {
    path,
    status: "ok",
    content: finalContent,
    ...(generatedIds.length > 0 && { generatedIds }),
  }
}
