import { parseCodeBlocks, replaceBlockContents, type CodeBlock } from "./parse"
import { resolveBlockLabel, getIdPaths } from "~/lib/data-blocks/registry"
import type { IdPathConfig } from "~/lib/data-blocks/definition"
import { tryParseJson, isObject, parsePath } from "./json"
import { ENTITY_ID_SUFFIX_RE } from "~/lib/utils/entity-id"

export interface GeneratedId {
  id: string
  type: string
  label: string | null
  source: string
}

type UuidMapping = Record<string, string>

interface FillIdsResult {
  content: string
  generated: GeneratedId[]
}

export const isSystemId = (id: string, prefix: string): boolean => {
  if (!id.startsWith(`${prefix}-`)) return false
  return ENTITY_ID_SUFFIX_RE.test(id.slice(prefix.length + 1))
}

export const replaceUuidPlaceholders = (
  content: string
): { result: string; generated: UuidMapping } => {
  const generated: UuidMapping = {}

  const result = content.replace(UUID_PLACEHOLDER_REGEX, (_, raw) => {
    const name = normalizePlaceholderName(raw)
    if (!(name in persistentIdMap)) {
      persistentIdMap[name] = generatePrefixedId(name)
    }
    generated[name] = persistentIdMap[name]
    return persistentIdMap[name]
  })

  return { result, generated }
}

export const fillDocIds = (doc: Record<string, unknown>, language: string): GeneratedId[] =>
  getIdPaths(language).flatMap((config) => fillIdPath(doc, config, language))

export const fillMissingIds = (markdown: string, originalContent?: string): FillIdsResult => {
  const updates = collectBlockUpdates(markdown, originalContent)
  if (updates.length === 0) {
    return { content: markdown, generated: [] }
  }

  const content = replaceBlockContents(markdown, updates)
  const generated = updates.flatMap((u) => u.ids)

  return { content, generated }
}

export const buildGeneratedIdsList = (
  placeholderMapping: UuidMapping,
  autoGenerated: GeneratedId[],
  markdown: string
): GeneratedId[] => {
  const all: GeneratedId[] = []

  const blocks = parseCodeBlocks(markdown)
  for (const [placeholder, id] of Object.entries(placeholderMapping)) {
    const block = blocks.find((b) => {
      const parsed = tryParseJson(b.content)
      return parsed?.id === id
    })

    if (block) {
      const parsed = tryParseJson(block.content)
      all.push({
        id,
        type: block.language,
        label: parsed ? getBlockLabel(parsed, block.language) : null,
        source: placeholder,
      })
    } else {
      all.push({ id, type: "unknown", label: null, source: placeholder })
    }
  }

  all.push(...autoGenerated)

  const unseen = all.filter(isUnshown)
  markShown(unseen)
  return unseen
}

export const formatGeneratedIds = (ids: GeneratedId[]): string => {
  if (ids.length === 0) return ""

  const lines = ids.map((g) => {
    const labelPart = g.label ? ` "${g.label}"` : ""
    const sourcePart = g.source === "none" ? "[none]" : `[${g.source}]`
    return `- ${g.id} for ${g.type} ${sourcePart}${labelPart}`
  })

  return `Generated IDs:\n${lines.join("\n")}`
}

const UUID_PLACEHOLDER_REGEX = /\[uuid-([^\]]+)\]/g

const persistentIdMap: UuidMapping = {}
const shownIds = new Set<string>()

export const generateShortId = (): string => {
  const digit = Math.floor(Math.random() * 10).toString()
  const rest = Math.random().toString(36).substring(2, 9)
  return digit + rest
}

const normalizePlaceholderName = (name: string): string =>
  name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")

const extractPrefix = (name: string): string => name.split("-")[0]

const generatePrefixedId = (name: string): string => `${extractPrefix(name)}-${generateShortId()}`

const shouldNormalizeId = (id: string, prefix: string, originalContent?: string): boolean => {
  if (isSystemId(id, prefix)) return false
  if (!originalContent) return false
  if (originalContent.includes(id)) return false
  return true
}

const resolveOrGenerateId = (malformedId: string, prefix: string): string => {
  if (malformedId in persistentIdMap) return persistentIdMap[malformedId]
  const newId = `${prefix}-${generateShortId()}`
  persistentIdMap[malformedId] = newId
  return newId
}

interface ResolvedId {
  newId: string
  source: string
}

const isMissingId = (id: unknown): boolean => id === undefined || id === null || id === ""

const resolveId = (
  currentValue: unknown,
  prefix: string,
  originalContent?: string
): ResolvedId | null => {
  if (isMissingId(currentValue)) {
    return { newId: `${prefix}-${generateShortId()}`, source: "none" }
  }
  if (typeof currentValue !== "string") return null
  if (!shouldNormalizeId(currentValue, prefix, originalContent)) return null
  return { newId: resolveOrGenerateId(currentValue, prefix), source: currentValue }
}

const getBlockLabel = (parsed: Record<string, unknown>, language: string): string | null => {
  const value = resolveBlockLabel(language, parsed)
  if (!value) return null
  return value.length > 40 ? value.slice(0, 40) + "..." : value
}

interface BlockUpdate {
  block: CodeBlock
  newContent: string
  ids: GeneratedId[]
}

const fillIdPath = (
  parsed: Record<string, unknown>,
  config: IdPathConfig,
  language: string,
  originalContent?: string
): GeneratedId[] => {
  const pathInfo = parsePath(config.path)
  if (!pathInfo) return []

  const ids: GeneratedId[] = []

  if (pathInfo.type === "root") {
    const resolved = resolveId(parsed[pathInfo.field], config.prefix, originalContent)
    if (resolved) {
      parsed[pathInfo.field] = resolved.newId
      ids.push({
        id: resolved.newId,
        type: language,
        label: getBlockLabel(parsed, language),
        source: resolved.source,
      })
    }
  } else if (pathInfo.type === "root-array") {
    if (!Array.isArray(parsed)) return ids

    for (const item of parsed) {
      if (!isObject(item)) continue
      const resolved = resolveId(item[pathInfo.itemField], config.prefix, originalContent)
      if (!resolved) continue
      item[pathInfo.itemField] = resolved.newId
      ids.push({
        id: resolved.newId,
        type: language,
        label: null,
        source: resolved.source,
      })
    }
  } else {
    const arr = parsed[pathInfo.arrayField]
    if (!Array.isArray(arr)) return ids

    for (const item of arr) {
      if (!isObject(item)) continue
      const resolved = resolveId(item[pathInfo.itemField], config.prefix, originalContent)
      if (!resolved) continue
      item[pathInfo.itemField] = resolved.newId
      ids.push({
        id: resolved.newId,
        type: `${language}.${pathInfo.arrayField}`,
        label: null,
        source: resolved.source,
      })
    }
  }

  return ids
}

const collectBlockUpdates = (markdown: string, originalContent?: string): BlockUpdate[] => {
  const blocks = parseCodeBlocks(markdown)
  const updates: BlockUpdate[] = []

  for (const block of blocks) {
    if (!block.language.startsWith("json-")) continue

    const parsed = tryParseJson(block.content)
    if (!parsed) continue

    const idPaths = getIdPaths(block.language)
    if (idPaths.length === 0) continue

    const ids: GeneratedId[] = []
    for (const config of idPaths) {
      ids.push(...fillIdPath(parsed, config, block.language, originalContent))
    }

    if (ids.length > 0) {
      updates.push({
        block,
        newContent: JSON.stringify(parsed, null, 2),
        ids,
      })
    }
  }

  return updates
}

const isUnshown = (entry: GeneratedId): boolean => !shownIds.has(entry.id)

const markShown = (entries: GeneratedId[]): void => {
  for (const entry of entries) shownIds.add(entry.id)
}
